interface Lead {
  id: string
  name: string
  contact: string
  company: string
  platform: string
  features: string[]
  budget: string
  score: number
  status: 'high' | 'medium' | 'low'
  date: string
}

const leads: Lead[] = [
  {
    id: 'lead-1',
    name: 'Amani Mwangi',
    contact: '+254 712 345678 (WhatsApp)',
    company: 'Soko Direct micro-savings',
    platform: 'Web & Mobile App',
    features: ['Real-Time Chat', 'Supabase Dashboard', 'AI Assistant'],
    budget: '$5,500',
    score: 88,
    status: 'high',
    date: '2 hours ago',
  },
  {
    id: 'lead-2',
    name: 'David Chen',
    contact: 'dchen@logistix.io',
    company: 'Logistix SaaS platform',
    platform: 'Web Application',
    features: ['Stripe Payments', 'Admin Analytics Panel'],
    budget: '$3,200',
    score: 52,
    status: 'medium',
    date: '1 day ago',
  },
  {
    id: 'lead-3',
    name: 'Fatma Juma',
    contact: '+254 789 123456 (WhatsApp)',
    company: 'Kikundi Social Chama',
    platform: 'Mobile App',
    features: ['Chat Engine', 'M-Pesa Webhooks'],
    budget: '$1,800',
    score: 28,
    status: 'low',
    date: '3 days ago',
  },
]

export default function LeadsTab() {
  return (
    <div className="flex-1 min-w-0 flex flex-col overflow-y-auto p-4 sm:p-6 xl:p-8 animate-fadeIn">
      <div className="w-full max-w-[1800px] mx-auto space-y-6">
        {/* Header and Stats */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
          <div>
            <h2 className="text-xl font-bold text-slate-100 glow-blue">High-Value Lead Tracking</h2>
            <p className="text-xs text-slate-400 mt-1">
              Real-time analytics and predictive scoring of incoming projects generated by external clients.
            </p>
          </div>
          <div className="flex gap-2">
            <span className="bg-red-950/40 text-red-400 text-[10px] px-3 py-1.5 rounded border border-red-500/20 font-mono font-bold uppercase tracking-wider flex items-center gap-1.5 animate-pulse">
              <span className="w-1.5 h-1.5 rounded-full bg-red-400"></span>
              Alerts: 1 High-Value Lead
            </span>
          </div>
        </div>

        {/* Global pipeline statistics */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          {[
            { label: 'Total Inquiries', val: '18 captured', color: 'text-cyan-400' },
            { label: 'High-Value Leads', val: '4 prospects', color: 'text-red-400' },
            { label: 'Pipeline Forecast', val: '$32,500 USD', color: 'text-emerald-400' },
          ].map((s, idx) => (
            <div key={idx} className="bg-[#03050a] border border-[#1a2238] p-4 rounded-xl font-mono text-center space-y-1">
              <span className="text-[9px] uppercase tracking-widest text-slate-500 block">{s.label}</span>
              <strong className={`text-sm font-bold block ${s.color}`}>{s.val}</strong>
            </div>
          ))}
        </div>

        {/* Leads List */}
        <div className="space-y-4">
          <span className="text-[10px] uppercase font-bold tracking-widest text-slate-500 font-mono block">Active Lead Queue</span>
          
          <div className="space-y-3">
            {leads.map((l) => (
              <div
                key={l.id}
                className={`p-5 rounded-xl bg-[#03050a] border transition-all duration-300 relative overflow-hidden flex flex-col md:flex-row justify-between items-start md:items-center gap-4 ${
                  l.status === 'high'
                    ? 'border-red-500/30 bg-gradient-to-r from-[#03050a] to-red-950/5 hover:border-red-500/50 shadow-[0_0_15px_rgba(239,68,68,0.05)]'
                    : l.status === 'medium'
                    ? 'border-[#1a2238] hover:border-cyan-500/30'
                    : 'border-[#1a2238]/60 opacity-75 hover:opacity-100 hover:border-slate-800'
                }`}
              >
                {/* Score Indicator Column */}
                <div className="flex items-center gap-4">
                  <div className={`w-14 h-14 rounded-xl border flex flex-col items-center justify-center shrink-0 font-mono ${
                    l.status === 'high'
                      ? 'border-red-500/25 bg-red-950/20 text-red-400'
                      : l.status === 'medium'
                      ? 'border-cyan-500/25 bg-cyan-950/20 text-cyan-400'
                      : 'border-slate-700 bg-slate-900/20 text-slate-400'
                  }`}>
                    <span className="text-xs uppercase font-medium text-[8px] tracking-wider block opacity-75">Score</span>
                    <strong className="text-lg font-extrabold tracking-tight">{l.score}</strong>
                  </div>

                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      <h4 className="text-sm font-bold text-slate-100">{l.name}</h4>
                      {l.status === 'high' && (
                        <span className="bg-red-950/50 text-red-400 text-[8px] font-bold px-1.5 py-0.5 rounded border border-red-500/20 uppercase tracking-widest font-mono">
                          High-Value
                        </span>
                      )}
                    </div>
                    <p className="text-xs text-slate-400">{l.company} • <span className="text-slate-500">{l.contact}</span></p>
                    <p className="text-[10px] text-slate-500 font-mono">{l.platform}</p>
                  </div>
                </div>

                {/* Features & Action Column */}
                <div className="flex flex-col md:items-end gap-2 text-xs md:text-right w-full md:w-auto border-t md:border-t-0 border-[#1a2238] pt-3 md:pt-0">
                  <div className="flex flex-wrap gap-1 md:justify-end">
                    {l.features.map((f) => (
                      <span key={f} className="bg-slate-900 text-slate-400 text-[9px] px-2 py-0.5 rounded border border-slate-800 font-mono">
                        {f}
                      </span>
                    ))}
                  </div>

                  <div className="flex justify-between md:justify-end items-center gap-4 text-[10px] font-mono text-slate-400 mt-1">
                    <span>Captured: <strong className="text-slate-200">{l.date}</strong></span>
                    <span>Budget: <strong className="text-emerald-400">{l.budget}</strong></span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}
